[2024-10-03T20:50:06.075+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T20:50:06.089+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.train_model scheduled__2024-10-03T20:45:00+00:00 [queued]>
[2024-10-03T20:50:06.101+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.train_model scheduled__2024-10-03T20:45:00+00:00 [queued]>
[2024-10-03T20:50:06.105+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-03T20:50:06.131+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): train_model> on 2024-10-03 20:45:00+00:00
[2024-10-03T20:50:06.155+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=545) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-03T20:50:06.163+0000] {standard_task_runner.py:72} INFO - Started process 579 to run task
[2024-10-03T20:50:06.163+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'train_model', 'scheduled__2024-10-03T20:45:00+00:00', '--job-id', '532', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpsa740rmv']
[2024-10-03T20:50:06.168+0000] {standard_task_runner.py:105} INFO - Job 532: Subtask train_model
[2024-10-03T20:50:06.274+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline.train_model scheduled__2024-10-03T20:45:00+00:00 [running]> on host e4a98f1dada1
[2024-10-03T20:50:06.356+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T20:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T20:45:00+00:00'
[2024-10-03T20:50:06.358+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T20:50:06.436+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff59712a50>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/create
[2024-10-03T20:50:10.673+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d784800>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/create
[2024-10-03T20:50:18.830+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d7844a0>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/create
[2024-10-03T20:50:35.555+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d784560>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/create
