[2024-10-03T16:05:07.058+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T16:05:07.392+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: data_preparation.clean_data scheduled__2024-10-03T14:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-10-03T16:05:07.453+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
