[2024-10-03T20:49:18.803+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T20:49:18.820+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.train_model scheduled__2024-10-03T20:40:00+00:00 [queued]>
[2024-10-03T20:49:18.830+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.train_model scheduled__2024-10-03T20:40:00+00:00 [queued]>
[2024-10-03T20:49:18.830+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-03T20:49:18.844+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): train_model> on 2024-10-03 20:40:00+00:00
[2024-10-03T20:49:18.856+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=379) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-03T20:49:18.855+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'train_model', 'scheduled__2024-10-03T20:40:00+00:00', '--job-id', '525', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpu8us6v9n']
[2024-10-03T20:49:18.860+0000] {standard_task_runner.py:72} INFO - Started process 421 to run task
[2024-10-03T20:49:18.861+0000] {standard_task_runner.py:105} INFO - Job 525: Subtask train_model
[2024-10-03T20:49:18.956+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline.train_model scheduled__2024-10-03T20:40:00+00:00 [running]> on host e4a98f1dada1
[2024-10-03T20:49:19.014+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T20:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T20:40:00+00:00'
[2024-10-03T20:49:19.015+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T20:49:19.109+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff5983fa10>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/create
[2024-10-03T20:49:23.476+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d770d70>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/create
[2024-10-03T20:49:32.418+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d770560>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/create
[2024-10-03T20:49:48.630+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d7709e0>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/create
[2024-10-03T20:50:21.009+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d772690>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/create
[2024-10-03T20:50:21.037+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d772090>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=MLflow+experiment+01
[2024-10-03T20:50:25.477+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d773d10>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=MLflow+experiment+01
[2024-10-03T20:50:33.902+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d773d70>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=MLflow+experiment+01
[2024-10-03T20:50:50.054+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff8d772480>: Failed to resolve 'airflow' ([Errno -2] Name or service not known)")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=MLflow+experiment+01
